# Generated by Django 5.2.8 on 2025-11-24 02:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todos', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='todo',
            options={'ordering': ['-created_at'], 'verbose_name': 'Todo', 'verbose_name_plural': 'Todos'},
        ),
        migrations.AddIndex(
            model_name='todo',
            index=models.Index(fields=['-created_at'], name='todos_todo_created_1ddebf_idx'),
        ),
        migrations.AddIndex(
            model_name='todo',
            index=models.Index(fields=['is_resolved'], name='todos_todo_is_reso_4b1c05_idx'),
        ),
    ]
